[package]
name = "code2prompt-python"
version = "3.2.0"
edition = "2024"

[lib]
name = "code2prompt_rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = { workspace = true }
code2prompt_core = { path = "../code2prompt-core" }
pyo3 = { workspace = true }
